### ISSUE TITLE
version detected 试了很多遍都是没有结果（方括号里是空白），还是说我没有找到output.csv在哪？

### ISSUE THREAD

**Issue by odys2061** [xswxm/Ticfirm-sniffer#1]
试过0-450000，1000-450000，412800-450000，漫长的等待后version detected没有结果，请问大大这是为什么？pip和python都是官方版本啊，sniffer也是GitHub下的最新版。Windows10家庭中文版64位正式版最新版，另一台Windows专业版正式版最新版也试了很多次都是version detected没有结果。我哪里操作错误了？

**Comment by xswxm** [comment]
确定app版本是对的吗

**Comment by odys2061** [comment]
> 确定app版本是对的吗

之前麻烦大佬了，我忘记关闭这个issue了😊现在换成了TicWatch C2国际版，已经无此忧虑🤗。
